-- AlterTable
ALTER TABLE "game_periods" ADD COLUMN     "total_eight_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_five_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_four_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_nine_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_one_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_seven_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_six_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_three_bets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_two_bets" DOUBLE PRECISION NOT NULL DEFAULT 0;
